services:
  - type: web
    runtime: node
    name: follystatus
    region: frankfurt
    plan: free
    branch: main
    buildCommand: cd ./web/follystatus/ && npm install
    startCommand: npx vite --host --port 8005
    repo: https://github.com/kapilpokhrel/follystatus.git
    autoDeploy: false
    envVars:
      - key: __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
        value: follystatus.onrender.com
