services:
  - type: web
    runtime: node
    name: follystatus
    region: frankfurt
    plan: free
    branch: main
    rootDir: web/follystatus
    buildCommand: npm install && npm run build
    startCommand: node src/server.js
    repo: https://github.com/kapilpokhrel/follystatus.git
    autoDeploy: false
    envVars:
      - key: OGImageBaseURL
        value: https://follystatus.onrender.com

  - type: web
    runtime: go
    name: follystatus-api
    region: frankfurt
    plan: free
    branch: main
    rootDir: cmd/follystatus
    buildCommand: go build -tags netgo -ldflags '-s -w' -o follystatusbin
    startCommand: ./follystatusbin
